version: '3.9'

services:
    back:
        container_name: back
        restart: always
        env_file:
            - ./.env
        build: 
            context: ./back
            target: dev
        volumes:
            - node_modules_back:/app/node_modules
            - ./back:/app
        ports:
            - "${API_PORT}:${API_PORT}"
        environment:
            DB_HOST: db       
        depends_on:
            - db
    front:
        container_name: front
        restart: always
        env_file:
            - ./.env
        build: ./front
        volumes:
            - node_modules_front:/app/node_modules
            - ./front:/app
            - ./.env:/app/.env
        ports:
            - "${CLIENT_PORT}:9000"
        depends_on:
            - back
    db:
        container_name: db
        restart: always
        image: postgres:15.3
        env_file:
            - ./.env
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
            PGDATA: /data/postgres
        volumes:
            - db:/data/postgres
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "${DB_PORT}:${DB_PORT}"

volumes:
    db:
        driver: local
    node_modules_back:
        driver: local
    node_modules_front:
        driver: local