name: "Deploy"

on:
  push:
    branches: ["dev"]

jobs:
  build-push-gce:
    permissions:
      contents: 'read'
      id-token: 'write'

    name: Build and Push to GCE
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: 'bubbly-upgrade-39550'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'

      - name: 'Google Auth'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_ID_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push back and front images using docker-compose
        run: |
          NODE_ENV=prod \
          AUTH_CONFIG=${{ secrets.AUTH_CONFIG }} \
          API_PORT=${{ secrets.API_PORT }} \
          CLIENT_PORT=${{ secrets.CLIENT_PORT }} \
          DB_NAME=${{ secrets.DB_NAME }} \
          DB_HOST=${{ secrets.DB_HOST }} \
          DB_USER=${{ secrets.DB_USER }} \
          DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          DB_PORT=${{ secrets.DB_PORT }} \
          PGADMIN_DEFAULT_EMAIL=${{ secrets.PGADMIN_DEFAULT_EMAIL }} \
          PGADMIN_DEFAULT_PASSWORD=${{ secrets.PGADMIN_DEFAULT_PASSWORD }} \
          PGADMIN_PORT=${{ secrets.PGADMIN_PORT }} \
          docker-compose --no-env-file -f docker-compose-prod.yml build
          docker tag back:latest ghcr.io/${{ github.repository }}/back:latest
          docker tag front:latest ghcr.io/${{ github.repository }}/front:latest
          docker push ghcr.io/${{ github.repository }}/back:latest
          docker push ghcr.io/${{ github.repository }}/front:latest
        # -
        #   name: Build and push
        #   uses: docker/build-push-action@v4
        #   with:
        #     push: true
        #     tags: user/app:lates