name: "Deploy"

on:
  push:
    branches: ["dev"]

jobs:
  build-push-gce:
    name: Build and Push to GCE
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: 'bubbly-upgrade-39550'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'

      - name: 'Google Auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_ID_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'